server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://mysql:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}

jpa:
  hibernate:
    dll-auto: update
  show-sql: true

jwt:
  signerKey: "Que8bPQKJl8xJ2rtzLkjGty+PLRhO1tvCeCRPypxmqvLRuH97sdNY6Xu6ADzBfxB"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in second